apiVersion: v1
kind: Pod
metadata:
  name: demo-kotlinapp
  lables:
    roles: webapp
spec:
  containers:
    - name: web
      image: rosinalexis/demo-kotline
      ports:
        - containerPort: 80
          name: web
          protocol: TCP
